ray_altitude_range: [-5, 50]
val_interval: 3000
ckpt_interval: 10000
coarse_samples: 256
fine_samples: 512
batch_size: 256
lr: 5e-4

photo_weight: 1.0
sigma_zeroinit: False
random_seed: 28
BARF: False
have_gt_poses: True
depth_weight: 1e-3