ray_altitude_range: [-5, 130]
val_interval: 3000
ckpt_interval: 10000
coarse_samples: 256
fine_samples: 512
batch_size: 256
no_bg_nerf: True
lr: 4e-4
lr_pose: 5e-7
train_iterations: 700000

BARF: True
BARF_start: 0.1
photo_weight: 1.0
depth_weight: 3e-3
sigma_zeroinit: True
random_seed: 3407
have_gt_poses: True
