ray_altitude_range: [-5, 120]
val_interval: 3000
ckpt_interval: 10000
batch_size: 256
lr: 5e-4
lr_pose: 0

photo_weight: 1.0
depth_weight: 0
sigma_zeroinit: False
random_seed: 28
pos_xyz_dim: 10
pos_dir_dim: 4
coarse_samples: 64
BARF: False
have_gt_poses: True

no_bg_nerf: True
use_cascade: True